### ISSUE TITLE
How do we reach the user's media query preference on first load?

### ISSUE THREAD

**Issue by mmartinsky** [mattstobbs/remix-dark-mode#1]
Great blog! One small note as I was reading through - looking through this example, I'm not sure I see how the user's default preference is respected on first load.

As I understand it, the request hits the `root.tsx`, at which point the loader will run. This calls `getThemeSession()`, which  appears will default to dark theme when the request has no session cookie (as should be expected for first hit). So when we get back to the root loader to render the app under `ThemeProvider`, `specifiedTheme` resolves as `'dark'`, rather than null. It seems like it will never reach `return getPreferredTheme();`

Example where it is defaulting to Dark, despite Light system preferences:
<img width="1161" alt="image" src="https://user-images.githubusercontent.com/9168958/158935233-2dddd344-a4a5-4089-b4a0-150e6d1a8141.png">

I think setting the fallback to null in https://github.com/mattstobbs/remix-dark-mode/blob/main/app/utils/theme.server.ts#L24 would do the trick.

**Comment by RichardHpa** [comment]
Thats your computers theme mode not your browsers

**Comment by mmartinsky** [comment]
Right, but Firefox by default uses your system theme

<img width="976" alt="image" src="https://user-images.githubusercontent.com/9168958/159488074-bd9c7a01-90fe-4826-85b1-2f9617d37898.png">

**Comment by mmartinsky** [comment]
https://github.com/remix-run/remix/pull/1661#discussion_r807415360 - this was addressed in the remix example!
